### ISSUE TITLE
Bilingual: Sanskrit - English

### ISSUE THREAD

**Issue by cittadhammo** [reader-dict/monolingual#2157] opened 2024-09-27 13:55 UTC
- Wiktionary page: https://en.wiktionary.org/wiki/%E0%A4%B8%E0%A4%82%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A5%83%E0%A4%A4
- Model link: I don't know what is the model link ... ;-)

We would like to have support for the sanskrit wiktionary in roman script with etymology
We have looked at your repo, but could not understand how to add a language ourselves. 

We were able to install venv and install dependencies, but the tests failed with Interrupted: 52 errors during collection

Thank you

**Comment by BoboTiG** [comment] 2024-09-27 15:09
You would like to have a full Sanskrit wiktionary?

**Comment by cittadhammo** [comment] 2024-09-27 16:22
Yes if possible.

**Comment by lasconic** [comment] 2024-09-27 18:22
Wiktionary in sanskrit is available at: https://sa.wiktionary.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0%E0%A4%AE%E0%A5%8D
If we make a version of this project for sanskrit, it means all words and definitions will be in sanskrit and not in english. Is that what you want ? How will you use such a dictionary ? on which device, and which format ?

**Comment by cittadhammo** [comment] 2024-09-28 16:32
Thank you for your reply! 

So what we would like is:

- **Target Words Language:** Sanskrit 
- **Website Language**: English
- **Final Outcome Format:** Stardict (for KOReader)
- Full Sanskrit Dictionary with Etymology information in English 

User case:

1. Sanskrit word appear in a book in Roman script OR I type the Sanskrit word in Roman script in the dictionary field
2. Entry word from Sanskrit-English Wiktionary dictionary appears as an option (in Devanagari script or Roman script.)
3. Click on the entry word
4. See the definition with Etymology

Example with browser: 

1. dharma is धर्म (via https://arshavidya.org.uk/vyasa.html)
3. -> https://en.wiktionary.org/wiki/धर्म
5. -> scroll to Sanskrit section
![image](https://github.com/user-attachments/assets/abdc19bc-d0e1-4f53-bdee-4193aafbd1bc)

Current Options:

- There is a Wiktionary available [here](https://github.com/Vuizur/Wiktionary-Dictionaries), but it does not include the Etymology or Pronunciation section of the Wiktionary.  
- The Wiktionary above is created via https://github.com/Vuizur/ebook_dictionary_creator
- Note: the transliteration seems automatic in KOReader from Roman to Devanagari script with that Wiktionary, or maybe the metadata of the entry include Roman script

**Comment by BoboTiG** [comment] 2024-09-29 06:10
It seems a duplicate of #973. For now, such a feature is not planned, but @lasconic provided some hint in #973, if you would like to try something.

**Closed by BoboTiG** 2024-09-29 06:10 UTC
Labels: locale:English

**Comment by lasconic** [comment] 2024-09-29 17:28
Yes, in short, this project is currently about monolingual dictionaries.

**Comment by BoboTiG** [comment] 2025-06-28 20:35
We now have the Sanskrit-English dictionary, go check the [reader.dict](https://www.reader-dict.com/get/sa/en) side project.

An example output with the word your shared @cittadhammo is shown below.

---

धर्म /dʱɐ́ɾ.mɐ/ · /d̪ʱɐɾ.mɐ/

<b>Noun</b> <i>m.</i>
  1. that which is established or firm, steadfast decree, statute, ordinance, law
      a. <i><b>c.</i> 1500 <small>BCE</small> – 1000 <small>BCE</small></b>, <i>Ṛgveda</i> 1.165.50:<dl><dd>य॒ज्ञेन॑ य॒ज्ञम् अ॑यजन्त दे॒वास् तानि॒ <b>धर्मा॑णि</b> प्रथ॒मान्य् आ॑सन् ।<br/> ते ह॒ नाकं॑ महि॒मानः॑ सचन्त॒ यत्र॒ पूर्वे॑ सा॒ध्याः सन्ति॑ दे॒वाः ॥<dl><dd><i>yajñéna yajñám ayajanta devā́s tā́ni <b>dhármāṇi</b> prathamā́ny āsan.<br/> té ha nā́kaṃ mahimā́naḥ sacanta yátra pū́rve sādhyā́ḥ sánti devā́ḥ.</i></dd><dd>By means of rite the Gods performed their rite: these were the earliest <b>ordinances</b>.<br/>These Mighty Ones attained the height of heaven, there where the Sadhyas, Gods of old, are dwelling.</dd></dl></dd></dl>
  2. morality, virtue, righteousness, moral code, good deed
      a. <i><b>c.</i> 400 <small>BCE</small></b>, <i>Bhagavad Gītā</i> IV.8:<dl><dd>परित्राणाय साधूनां विनाशाय च दुष्कृताम्।<br/><b>धर्म</b>संस्थापनार्थाय संभवामि युगे युगे॥<dl><dd><i>paritrāṇāya sādhūnāṃ vināśāya ca duṣkṛtām.<br/><b>dharma</b>saṃsthāpanārthāya saṃbhavāmi yuge yuge.</i></dd><dd>[And the Lord said:] To save the pious and destroy evil, and to reestablish <b>virtue</b>, I appear eon after eon.</dd></dl></dd></dl>
      b. <i><b>c.</i> 200 <small>BCE</small> – 200 <small>CE</small></b>, <i>Manusmṛti</i> 8.15:<dl><dd><b>धर्म</b> एव हतो हन्ति <b>धर्मो</b> रक्षति रक्षितः ।<br/>तस्माद् <b>धर्मो</b> न हन्तव्यो मा नो <b>धर्मो</b> हतो ऽवधीत् ॥<dl><dd><i><b>dharma</b> eva hato hanti <b>dharmo</b> rakṣati rakṣitaḥ.<br/>tasmād <b>dharmo</b> na hantavyo mā no <b>dharmo</b> hato ʼvadhīt.</i></dd><dd><b>Virtue</b> that has been violated [in turn] destroys [the individual]; <b>virtue</b> that has been protected [in turn] protects [the individual].<br/>Therefore, <b>virtue</b> is not to be violated, lest the violated <b>virtue</b> destroy us.</dd></dl></dd></dl>
  3. usage, practice, customary observance or prescribed conduct, duty
  4. right, justice (often as a synonym of punishment)
  5. religion, religious merit
  6. Law or Justice personified
  7. the law or doctrine of Buddhism
  8. the ethical precepts of Buddhism
  9. the law of Northern Buddhism
 10. nature, character, peculiar condition or essential quality, property, mark, peculiarity


From Proto-Indo-European <i>&#42;dʰér-mos</i>, from <i>&#42;dʰer-</i> (“to hold, support”); the Sanskrit root is <i>धृ</i> (dhṛ). Cognate with Latin <i>firmus</i> (“stable, strong”) (whence also English <i>firm</i>).
